export const BASE_URLS = {
    AUTH_URL: process.env.NEXT_PUBLIC_AUTH_BASE_URL!,
    ORGANIZATION_URL: process.env.NEXT_PUBLIC_ORGANIZATION_BASE_URL!,

    GPX_BASE_URL: process.env.NEXT_PUBLIC_GPX_BASE_URL!,
    GPX_WS_HOST: process.env.NEXT_PUBLIC_GPX_WS_HOST!,
    API_URL: process.env.NEXT_PUBLIC_API_BASE_URL!,
    TNT_URL: process.env.NEXT_PUBLIC_TNT_BASE_URL!,
    DATA_URL: process.env.NEXT_PUBLIC_DATA_BASE_URL!,
    ENTITY_URL: process.env.NEXT_PUBLIC_ENTITY_BASE_URL!,
    WORKFLOW_URL: process.env.NEXT_PUBLIC_WORKFLOW_BASE_URL!,
    BACKOFFICE_URL: process.env.NEXT_PUBLIC_BACKOFFICE_API_BASE_URL!,
    SSO_URL: process.env.NEXT_PUBLIC_SSO_API_BASE_URL!,
}